apiVersion: v2
name: mirror
description: A Helm chart to deploy mc mirror across two AWS S3 API Compatible systems.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of mc. 
appVersion: RELEASE.2019-10-09T22-54-57Z
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
