apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mirror.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "mirror.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "mirror.fullname" . }}
    spec:
      volumes:
        - name: minio-configuration
          projected:
            sources:
            - configMap:
                name: {{ include "mirror.fullname" . }}
      containers:
        - name: {{ template "mirror.fullname" . }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end}}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "/config/initialize"]
          volumeMounts:
          - name: minio-configuration
            mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}